# Generated by Django 3.1.7 on 2021-03-29 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=200)),
                ('segundo_nombre', models.CharField(blank=True, max_length=200)),
                ('primer_apellido', models.CharField(max_length=200)),
                ('segundo_apellido', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.BigIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caratula', models.ImageField(upload_to='caratulas')),
                ('nombre', models.CharField(max_length=200)),
                ('plataforma', models.CharField(choices=[('PlayStation 5', 'PlayStation 5'), ('XBOX Series', 'XBOX Series'), ('PlayStation 4', 'PlayStation 4'), ('Xbox ONE', 'XBOXONE'), ('PC', 'PC'), ('Nintendo Switch', 'Nintendo Switch')], default='PlayStation 4', max_length=50)),
                ('genero', models.CharField(choices=[('Accion y Aventuras', 'Accion y Aventuras'), ('Juegos de Mesa', 'Juegos de Mesa'), ('Familiar', 'Familiar'), ('Lucha', 'Lucha'), ('Plataformas', 'Plataformas'), ('Puzzles', 'Puzzles'), ('Carreras', 'Carreras'), ('Juegos de Rol', 'Juegos de Rol'), ('FPS', 'FPS'), ('Simulacion', 'Simulacion'), ('Deportes', 'Deportes'), ('Estrategia', 'Estrategia')], default='Accion y Aventuras', max_length=50)),
                ('clasificacion', models.CharField(blank=True, choices=[('E', 'TODOS'), ('E+10', 'TODOS+10'), ('T', 'ADOLESCENTES'), ('M', 'ADULTOS'), ('RP', 'PENDIENTE')], default='E', max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_lanzamiento', models.DateTimeField(blank=True)),
                ('precio', models.FloatField(blank=True)),
                ('stock', models.IntegerField(blank=True)),
                ('tags', models.ManyToManyField(to='cuentas.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, null=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('NO DISPONIBLE', 'NO DISPONIBLE'), ('ENTREGADO', 'ENTREGADO')], max_length=200, null=True)),
                ('nota', models.CharField(max_length=1000, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.cliente')),
                ('videojuego', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.videojuego')),
            ],
        ),
    ]
