# Generated by Django 3.1.7 on 2021-05-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_auto_20210511_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='perfil_foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
